### ISSUE TITLE
Mangos 2 (WotlK) version ?

### ISSUE THREAD

**Issue by fly-man-** [StephenSorriaux/mangosone-docker#1]
Are you able to create a version of this for WotlK as well ??

**Comment by StephenSorriaux** [comment]
Yes, I coud do that since it is very similar to the first mangos.

I will add it when I get some free time and update this issue.

**Comment by fly-man-** [comment]
Thank you very much :)

**Comment by StephenSorriaux** [comment]
I just added the 3 images for MangosTwo in PR #2, if you can give it a try and give me a feedback it would be great as I currently don't have WotlK available.

Thanks

**Comment by fly-man-** [comment]
I will have a look when I am back at my office next Monday.

Cool to see how you did it this quick.

**Comment by fly-man-** [comment]
Worked like a charm, * thumbs up *

**Comment by StephenSorriaux** [comment]
Thanks for your feedback!
