### ISSUE TITLE
/mangosconf/ahbot.conf not loading - easy fix

### ISSUE THREAD

**Issue by jpfingstmann** [StephenSorriaux/mangosone-docker#22]
I added the mount to /mangosconf/ahbot.conf and was getting:
`2019-07-14 07:47:37 Initialize AuctionHouseBot...
2019-07-14 07:47:37 AHBOT is Disabled. Unable to open configuration file /server/install/etc/ahbot.conf. `

I checked and /mangosconf/ahbot.conf exists, I noticed the launch_mangosd.conf file has the following:
`AHCONFIG=-a /mangosconf/ahbot.conf`
I replaced it with:
`AHCONFIG="-a /mangosconf/ahbot.conf"`

This fixed it for me.

**Comment by StephenSorriaux** [comment]
Hi,

You are right, this is now fixed, thank you.
