### ISSUE TITLE
[Issue] [mangos-two] Segmentation fault on line 39 [latest] [23/1/2020: 23:33]

### ISSUE THREAD

**Issue by braddevans** [StephenSorriaux/mangosone-docker#23]
### Issue
./launch_mangosd.sh line 39
triggers a segmentation fault

### command: 
```
sudo docker run -e "LOGIN_DATABASE_INFO=192.168.1.37;3306;root;redacted;realmd" -e "WORLD_DATABASE_INFO=192.168.1.37;3306;root;redacted;mangos2" -e "CHARACTER_DATABASE_INFO=192.168.1.37;3306;root;redacted;character2" -p 8085:8085 -v /home/docker/worldofwarcraft/mangosd.conf:/mangosconf/mangosd.conf -v /home/docker/worldofwarcraft/maps:/etc/mangos/maps -v /home/docker/worldofwarcraft/mmaps:/etc/mangos/mmaps -v /home/docker/worldofwarcraft/vmaps:/etc/mangos/vmaps -v /home/docker/worldofwarcraft/dbc:/etc/mangos/dbc ssorriaux/mangostwo-server
```

### Directory:
![dir](https://user-images.githubusercontent.com/7889253/61314467-9084ec80-a7f4-11e9-9465-ee633d9d6fba.PNG)

### Log:
[mangos-terminal-log.log](https://github.com/StephenSorriaux/mangos-docker/files/3398251/mangos-terminal-log.log)

### Mangosd config file:
[mangosd.conf.log](https://github.com/StephenSorriaux/mangos-docker/files/3398259/mangosd.conf.log)

### Maps
the maps are known working since i have tested a copy of them on the windows version of mangostwo.

**Comment by StephenSorriaux** [comment]
Hi,

I don't see the `-i` parameter in your `docker run` command  that keeps the STDIN opened. Can you please try adding the parameter?

**Comment by braddevans** [comment]
oh thanks that was the issue

**Comment by StephenSorriaux** [comment]
Sure, have fun.

**Comment by braddevans** [comment]
```bash
sudo docker run -it -d \
	-e "LOGIN_DATABASE_INFO=192.168.2.5;3306;root;mangos;realmd" \
	-e "WORLD_DATABASE_INFO=192.168.2.5;3306;root;mangos;mangos2" \
	-e "CHARACTER_DATABASE_INFO=192.168.2.5;3306;root;mangos;character2" \
	-p 8085:8085 \
	-v /home/docker/gameservers/worldofwarcraft/config/:/mangosconf/ \
	-v /home/docker/gameservers/worldofwarcraft/maps:/etc/mangos/maps \
	-v /home/docker/gameservers/worldofwarcraft/mmaps:/etc/mangos/mmaps \
	-v /home/docker/gameservers/worldofwarcraft/vmaps:/etc/mangos/vmaps \
	-v /home/docker/gameservers/worldofwarcraft/dbc:/etc/mangos/dbc \
	ssorriaux/mangostwo-server
```
same seg fault issue even with interactive
[std_out.txt](https://github.com/StephenSorriaux/mangos-docker/files/4106090/std_out.txt)

**Comment by mightymiracleman** [comment]
Hello!  I stumbled across this issue as I was running into this problem in K8s; I have server deployment successfully starting, but it crashes as soon as it hits the mangos prompt (I get that same segmentation error mentioned above).  I did some searching to see if it was possible to leave the STDIN open on the Pod / Container as you suggested above but I'm not having much luck finding how to do this in k8s.  

Thank you!

**Comment by StephenSorriaux** [comment]
Hey,

OK, I see, I will do some testing tomorrow and let you know. Is it also for Mangos 2?

**Comment by mightymiracleman** [comment]
Yep!  I can give you additional info if you need it.  Thanks so much!

**Comment by StephenSorriaux** [comment]
@mightymiracleman I just pushed some updates and was able to get the DB, realmd and almost the server running (I dont have the maps available right now). Can you please retry using the latest [`kubernete-deployment.yml` file](https://github.com/StephenSorriaux/mangos-docker/blob/master/mangostwo/kubernetes-deployment.yml)? As the problem was mainly from some changes in the DB, you will need to delete the PVC used by the database statefulset so that it will perform a full generation of the DB. I also changed all the `mangos*-server` containers to include the `stdin: true` and `tty: true` configuration.

**Comment by mightymiracleman** [comment]
I blew it all away and re deployed; I just added PV / PVC for the volumes (like I had it) looks like it's up!  Thank you!

**Comment by StephenSorriaux** [comment]
Thank you for your feedback!

@braddevans FWIW, those commits also fix the latest issue you mentioned.
