### ISSUE TITLE
Kubernetes mangoszero Segmentation fault

### ISSUE THREAD

**Issue by filipdadgar** [StephenSorriaux/mangosone-docker#27]
Hi there!

Love the work!

I've ran a few tries on k8s with my own modification of the repo files to eg get AI BOT enabled during build, but somehow I keep getting this error in Mangosd pod:

./launch_mangosd.sh: line 39:    11 Segmentation fault      (core dumped) ${BINDIR}/mangosd -c $CONFIGS/mangosd.conf ${AHCONFIG}

I've also tried the k8 deployment file found in mangoszero repo here and only change I've done is to remove the PVC (persistent volume claim) to map with my own and still getting same error:

What am I missing? Do I need to make sure that the configs already exist somewhere? Documentation doesnt state that (except for AHBOT)

Thanks in advance!

**Comment by StephenSorriaux** [comment]
Hey!

Maybe my latest builds are just broken, I will do some testing on my side and come back to you.

**Comment by StephenSorriaux** [comment]
Hello,

I just pushed a new build but I currently don't have the maps to ensure everything is fine. Can you check if the new version runs fine without anything related to the AI bot?
If it does raise an error, please add some more logs so that I get some context.

Thanks!

**Comment by filipdadgar** [comment]
Thank you, I will do that as soon as I get a chance. The deployment files are ready and I will happily share them with you.

**Comment by filipdadgar** [comment]
Hi,

Ok, I got the same error and after some extensive (no logs or debug flag would help) I realized there is something in the mangosd.conf file. When I ran with the default one things worked better! :)

Thank you for this.

**Comment by StephenSorriaux** [comment]
Hi,

Great to know everything is fine! I'm closing this for now, feel free to reopen it in case you encounter any similar problem.
